version: '2'
services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "bundle install && yarn install && bundle exec rake foreman:dev --trace"
    environment:
      - OVERRIDE_DB_HOST=db
      - OVERRIDE_DB_PASSWORD=
      - REDIS_URL=redis://redis:6379
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: 'postgres:10.6-alpine'
    ports:
      - "5432:5432"

  redis:
    image: 'redis:5.0.1-alpine'
    ports:
      - "6379:6379"

  mail:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
